apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: 975050297639.dkr.ecr.ap-south-1.amazonaws.com/rag-chunking:api-latest
        ports:
        - containerPort: 3001  # app port inside container

---
apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  type: LoadBalancer
  selector:
    app: api
  ports:
    - port: 80          # exposed to internet
      targetPort: 3001  # inside container
