apiVersion: apps/v1
kind: Deployment
metadata:
  name: text-extractor-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: text-extractor
  template:
    metadata:
      labels:
        app: text-extractor
    spec:
      containers:
      - name: text-extractor
        image: 975050297639.dkr.ecr.ap-south-1.amazonaws.com/rag-chunking:text-extractor-latest  # Text Extractor Image URI
        ports:
        - containerPort: 5002  # Assuming a different port for text extractor
        envFrom:
        - secretRef:
            name: text-extractor-env

---
apiVersion: v1
kind: Service
metadata:
  name: text-extractor-service
spec:
  type: LoadBalancer
  selector:
    app: text-extractor
  ports:
    - port: 80
      targetPort: 5002
