apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker
        image: <account>.dkr.ecr.<region>.amazonaws.com/<repo>:worker-latest
        envFrom:
        - secretRef:
            name: worker-env
